.TH wl2url 1 
.SH NAME
wl2url - a simple utility for converting a .webloc file to a .url file
.SH SYNOPSIS
wl2url [-dhnqv] [-o dir] files
.SH DESCRIPTION
wl2url is a simple utility for converting MacOSX .webloc files into 
Microsoft internet shortcuts (.url).  

Historically, .webloc files stored the url is stored in their resource 
fork, which was generally only accessible on MacOS or MacOSX.  Internet
shortcuts (.url) are plain-text files, which can be read on any platform.

wl2url relies on DeRez(1) (if available) and falls back to strings(1).
.SH OPTIONS
.TP
.B \-d
Delete the original webloc file after creating the url file
.TP
.B \-h
Prints a help message
.TP
.B \-n
Don't create a file, just print out the url
.TP
.B \-q
Quiet mode; only print out error messages
.TP
.B \-s
Use strings(1) instead of DeRez(1). By default DeRez(1) is used, if available.
.TP
.B \-v
Prints the version
.TP
.B \-o [dir]
Put the output files in [dir]
.SH SEE ALSO
DeRez(1), strings(1)
.SH PLATFORMS
wl2url has been tested on MacOSX 10.4+
.SH HISTORY
The wl2url command was written by Sriranga Veeraraghavan <ranga@calalum.org>.
